# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 332db0bea7c493c770c2f39e303a3135b68af0d1dedc99bee5673477ecb1d07a58e66a001653336614ee095eedfd9f6a329b5a89343bb2e63e73c18ac033477f

test:
  secret_key_base: 0b7859d2e26457db46140c9272542a58a24753726c219785ed3d7a2a738f9773f30ab8226d594dc256c2b4ce3e1712d3ee4108e47ea212d4d1726b0456c8952e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
